### PR TITLE
fix dns issue on pks (5X)

### PR DESCRIPTION
**Pull request by dujialun**

### CODE REVIEW

**Comment by goutamtadi1** [comment]
+2

We were able to cherry-pick the commits from this PR into `5X_STABLE` and create a new gpdb binary package that we deployed to a Kubernetes based GPDB cluster.

We successfully tested that names were resolving correctly and primary/mirror failover and fail-back worked fine.

Goutam & Jemish

**Review by slari-pivotal — APPROVED** [review]
We have not tested the code changes, but they look fine on visual inspection.

Please make sure it passes a clone of 5X_STABLE pipeline before merging.

Also, is this going to be forward-merged to the master branch?

**Comment by professor** [comment]
I was curious why we are doing a pull request to `5X_STABLE` and then forward porting to master. Normally we do pull requests to `master` and then back-port to `5X_STABLE`

Thanks!

**Comment by dujialun** [comment]
@professor This PR is just for providing the sample code, we will pull it to master first if the code is OK.

**Pull request closed without merging**
